// Türkiye il → ilçe adları (packages/cargo/src/tr-provinces.ts ile aynı; 81 il).
// Kargo adres doğrulaması için: il alanına ilçe yazılmış adresleri düzeltmekte kullanılır.
export const TR_PROVINCES: Record<string, string[]> = {
  "Adana": ["Aladağ", "Ceyhan", "Feke", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir", "Çukurova", "İmamoğlu"],
  "Adıyaman": ["Besni", "Gerger", "Gölbaşı", "Kahta", "Merkez", "Samsat", "Sincik", "Tut", "Çelikhan"],
  "Afyonkarahisar": ["Bayat", "Başmakçı", "Bolvadin", "Dazkırı", "Dinar", "Emirdağ", "Evciler", "Hocalar", "Kızılören", "Merkez", "Sandıklı", "Sinanpaşa", "Sultandağı", "Çay", "Çobanlar", "İhsaniye", "İscehisar", "Şuhut"],
  "Ağrı": ["Diyadin", "Doğubayazıt", "Eleşkirt", "Hamur", "Merkez", "Patnos", "Taşlıçay", "Tutak"],
  "Amasya": ["Göynücek", "Gümüşhacıköy", "Hamamözü", "Merkez", "Merzifon", "Suluova", "Taşova"],
  "Ankara": ["Akyurt", "Altındağ", "Ayaş", "Bala", "Beypazarı", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kahramankazan", "Kalecik", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Yenimahalle", "Çamlıdere", "Çankaya", "Çubuk", "Şereflikoçhisar"],
  "Antalya": ["Akseki", "Aksu", "Alanya", "Demre", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik", "İbradı"],
  "Artvin": ["Ardanuç", "Arhavi", "Borçka", "Hopa", "Kemalpaşa", "Merkez", "Murgul", "Yusufeli", "Şavşat"],
  "Aydın": ["Bozdoğan", "Buharkent", "Didim", "Efeler", "Germencik", "Karacasu", "Karpuzlu", "Koçarlı", "Kuyucak", "Kuşadası", "Köşk", "Nazilli", "Sultanhisar", "Söke", "Yenipazar", "Çine", "İncirliova"],
  "Balıkesir": ["Altıeylül", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "Karesi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Susurluk", "Sındırgı", "İvrindi"],
  "Bilecik": ["Bozüyük", "Gölpazarı", "Merkez", "Osmaneli", "Pazaryeri", "Söğüt", "Yenipazar", "İnhisar"],
  "Bingöl": ["Adaklı", "Genç", "Karlıova", "Kiğı", "Merkez", "Solhan", "Yayladere", "Yedisu"],
  "Bitlis": ["Adilcevaz", "Ahlat", "Güroymak", "Hizan", "Merkez", "Mutki", "Tatvan"],
  "Bolu": ["Dörtdivan", "Gerede", "Göynük", "Kıbrıscık", "Mengen", "Merkez", "Mudurnu", "Seben", "Yeniçağa"],
  "Burdur": ["Altınyayla", "Ağlasun", "Bucak", "Gölhisar", "Karamanlı", "Kemer", "Merkez", "Tefenni", "Yeşilova", "Çavdır", "Çeltikçi"],
  "Bursa": ["Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım", "İnegöl", "İznik"],
  "Çanakkale": ["Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Merkez", "Yenice", "Çan"],
  "Çankırı": ["Atkaracalar", "Bayramören", "Eldivan", "Ilgaz", "Korgun", "Kurşunlu", "Kızılırmak", "Merkez", "Orta", "Yapraklı", "Çerkeş", "Şabanözü"],
  "Çorum": ["Alaca", "Bayat", "Boğazkale", "Dodurga", "Kargı", "Laçin", "Mecitözü", "Merkez", "Ortaköy", "Osmancık", "Oğuzlar", "Sungurlu", "Uğurludağ", "İskilip"],
  "Denizli": ["Acıpayam", "Babadağ", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Buldan", "Güney", "Honaz", "Kale", "Merkezefendi", "Pamukkale", "Sarayköy", "Serinhisar", "Tavas", "Çal", "Çameli", "Çardak", "Çivril"],
  "Diyarbakır": ["Bağlar", "Bismil", "Dicle", "Ergani", "Eğil", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir", "Çermik", "Çüngüş", "Çınar"],
  "Edirne": ["Enez", "Havsa", "Keşan", "Lalapaşa", "Meriç", "Merkez", "Süloğlu", "Uzunköprü", "İpsala"],
  "Elazığ": ["Alacakaya", "Arıcak", "Ağın", "Baskil", "Karakoçan", "Keban", "Kovancılar", "Maden", "Merkez", "Palu", "Sivrice"],
  "Erzincan": ["Kemah", "Kemaliye", "Merkez", "Otlukbeli", "Refahiye", "Tercan", "Çayırlı", "Üzümlü", "İliç"],
  "Erzurum": ["Aziziye", "Aşkale", "Horasan", "Hınıs", "Karayazı", "Karaçoban", "Köprüköy", "Narman", "Oltu", "Olur", "Palandöken", "Pasinler", "Pazaryolu", "Tekman", "Tortum", "Uzundere", "Yakutiye", "Çat", "İspir", "Şenkaya"],
  "Eskişehir": ["Alpu", "Beylikova", "Günyüzü", "Han", "Mahmudiye", "Mihalgazi", "Mihalıççık", "Odunpazarı", "Sarıcakaya", "Seyitgazi", "Sivrihisar", "Tepebaşı", "Çifteler", "İnönü"],
  "Gaziantep": ["Araban", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Yavuzeli", "İslahiye", "Şahinbey", "Şehitkamil"],
  "Giresun": ["Alucra", "Bulancak", "Dereli", "Doğankent", "Espiye", "Eynesil", "Görele", "Güce", "Keşap", "Merkez", "Piraziz", "Tirebolu", "Yağlıdere", "Çamoluk", "Çanakçı", "Şebinkarahisar"],
  "Gümüşhane": ["Kelkit", "Köse", "Kürtün", "Merkez", "Torul", "Şiran"],
  "Hakkari": ["Derecik", "Merkez", "Yüksekova", "Çukurca", "Şemdinli"],
  "Hatay": ["Altınözü", "Antakya", "Arsuz", "Belen", "Defne", "Dörtyol", "Erzin", "Hassa", "Kumlu", "Kırıkhan", "Payas", "Reyhanlı", "Samandağ", "Yayladağı", "İskenderun"],
  "Isparta": ["Aksu", "Atabey", "Eğirdir", "Gelendost", "Gönen", "Keçiborlu", "Merkez", "Senirkent", "Sütçüler", "Uluborlu", "Yalvaç", "Yenişarbademli", "Şarkikaraağaç"],
  "Mersin": ["Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir", "Çamlıyayla"],
  "İstanbul": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bahçelievler", "Bakırköy", "Bayrampaşa", "Bağcılar", "Başakşehir", "Beykoz", "Beylikdüzü", "Beyoğlu", "Beşiktaş", "Büyükçekmece", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kartal", "Kağıthane", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Tuzla", "Zeytinburnu", "Çatalca", "Çekmeköy", "Ümraniye", "Üsküdar", "Şile", "Şişli"],
  "İzmir": ["Aliağa", "Balçova", "Bayraklı", "Bayındır", "Bergama", "Beydağ", "Bornova", "Buca", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kiraz", "Konak", "Kınık", "Menderes", "Menemen", "Narlıdere", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla", "Çeşme", "Çiğli", "Ödemiş"],
  "Kars": ["Akyaka", "Arpaçay", "Digor", "Kağızman", "Merkez", "Sarıkamış", "Selim", "Susuz"],
  "Kastamonu": ["Abana", "Araç", "Azdavay", "Ağlı", "Bozkurt", "Cide", "Daday", "Devrekani", "Doğanyurt", "Hanönü", "Küre", "Merkez", "Pınarbaşı", "Seydiler", "Taşköprü", "Tosya", "Çatalzeytin", "İhsangazi", "İnebolu", "Şenpazar"],
  "Kayseri": ["Akkışla", "Bünyan", "Develi", "Felahiye", "Hacılar", "Kocasinan", "Melikgazi", "Pınarbaşı", "Sarıoğlan", "Sarız", "Talas", "Tomarza", "Yahyalı", "Yeşilhisar", "Özvatan", "İncesu"],
  "Kırklareli": ["Babaeski", "Demirköy", "Kofçaz", "Lüleburgaz", "Merkez", "Pehlivanköy", "Pınarhisar", "Vize"],
  "Kırşehir": ["Akpınar", "Akçakent", "Boztepe", "Kaman", "Merkez", "Mucur", "Çiçekdağı"],
  "Kocaeli": ["Başiskele", "Darıca", "Derince", "Dilovası", "Gebze", "Gölcük", "Kandıra", "Karamürsel", "Kartepe", "Körfez", "Çayırova", "İzmit"],
  "Konya": ["Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadim", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak", "Çeltik", "Çumra"],
  "Kütahya": ["Altıntaş", "Aslanapa", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Hisarcık", "Merkez", "Pazarlar", "Simav", "Tavşanlı", "Çavdarhisar", "Şaphane"],
  "Malatya": ["Akçadağ", "Arapgir", "Arguvan", "Battalgazi", "Darende", "Doğanyol", "Doğanşehir", "Hekimhan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Yeşilyurt"],
  "Manisa": ["Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kula", "Köprübaşı", "Kırkağaç", "Salihli", "Saruhanlı", "Sarıgöl", "Selendi", "Soma", "Turgutlu", "Yunusemre", "Şehzadeler"],
  "Kahramanmaraş": ["Afşin", "Andırın", "Dulkadiroğlu", "Ekinözü", "Elbistan", "Göksun", "Nurhak", "Onikişubat", "Pazarcık", "Türkoğlu", "Çağlayancerit"],
  "Mardin": ["Artuklu", "Dargeçit", "Derik", "Kızıltepe", "Mazıdağı", "Midyat", "Nusaybin", "Savur", "Yeşilli", "Ömerli"],
  "Muğla": ["Bodrum", "Dalaman", "Datça", "Fethiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Menteşe", "Milas", "Ortaca", "Seydikemer", "Ula", "Yatağan"],
  "Muş": ["Bulanık", "Hasköy", "Korkut", "Malazgirt", "Merkez", "Varto"],
  "Nevşehir": ["Acıgöl", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Merkez", "Ürgüp"],
  "Niğde": ["Altunhisar", "Bor", "Merkez", "Ulukışla", "Çamardı", "Çiftlik"],
  "Ordu": ["Akkuş", "Altınordu", "Aybastı", "Fatsa", "Gölköy", "Gülyalı", "Gürgentepe", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Perşembe", "Ulubey", "Çamaş", "Çatalpınar", "Çaybaşı", "Ünye", "İkizce"],
  "Rize": ["Ardeşen", "Derepazarı", "Fındıklı", "Güneysu", "Hemşin", "Kalkandere", "Merkez", "Pazar", "Çamlıhemşin", "Çayeli", "İkizdere", "İyidere"],
  "Sakarya": ["Adapazarı", "Akyazı", "Arifiye", "Erenler", "Ferizli", "Geyve", "Hendek", "Karapürçek", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Sapanca", "Serdivan", "Söğütlü", "Taraklı"],
  "Samsun": ["19 Mayıs", "Alaçam", "Asarcık", "Atakum", "Ayvacık", "Bafra", "Canik", "Havza", "Kavak", "Ladik", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü", "Yakakent", "Çarşamba", "İlkadım"],
  "Siirt": ["Baykan", "Eruh", "Kurtalan", "Merkez", "Pervari", "Tillo", "Şirvan"],
  "Sinop": ["Ayancık", "Boyabat", "Dikmen", "Durağan", "Erfelek", "Gerze", "Merkez", "Saraydüzü", "Türkeli"],
  "Sivas": ["Akıncılar", "Altınyayla", "Divriği", "Doğanşar", "Gemerek", "Gölova", "Gürün", "Hafik", "Kangal", "Koyulhisar", "Merkez", "Suşehri", "Ulaş", "Yıldızeli", "Zara", "İmranlı", "Şarkışla"],
  "Tekirdağ": ["Ergene", "Hayrabolu", "Kapaklı", "Malkara", "Marmaraereğlisi", "Muratlı", "Saray", "Süleymanpaşa", "Çerkezköy", "Çorlu", "Şarköy"],
  "Tokat": ["Almus", "Artova", "Başçiftlik", "Erbaa", "Merkez", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Turhal", "Yeşilyurt", "Zile"],
  "Trabzon": ["Akçaabat", "Araklı", "Arsin", "Beşikdüzü", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Maçka", "Of", "Ortahisar", "Sürmene", "Tonya", "Vakfıkebir", "Yomra", "Çarşıbaşı", "Çaykara", "Şalpazarı"],
  "Tunceli": ["Hozat", "Mazgirt", "Merkez", "Nazımiye", "Ovacık", "Pertek", "Pülümür", "Çemişgezek"],
  "Şanlıurfa": ["Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Eyyübiye", "Halfeti", "Haliliye", "Harran", "Hilvan", "Karaköprü", "Siverek", "Suruç", "Viranşehir"],
  "Uşak": ["Banaz", "Eşme", "Karahallı", "Merkez", "Sivaslı", "Ulubey"],
  "Van": ["Bahçesaray", "Başkale", "Edremit", "Erciş", "Gevaş", "Gürpınar", "Muradiye", "Saray", "Tuşba", "Çaldıran", "Çatak", "Özalp", "İpekyolu"],
  "Yozgat": ["Akdağmadeni", "Aydıncık", "Boğazlıyan", "Kadışehri", "Merkez", "Saraykent", "Sarıkaya", "Sorgun", "Yenifakılı", "Yerköy", "Çandır", "Çayıralan", "Çekerek", "Şefaatli"],
  "Zonguldak": ["Alaplı", "Devrek", "Ereğli", "Gökçebey", "Kilimli", "Kozlu", "Merkez", "Çaycuma"],
  "Aksaray": ["Ağaçören", "Eskil", "Gülağaç", "Güzelyurt", "Merkez", "Ortaköy", "Sarıyahşi", "Sultanhanı"],
  "Bayburt": ["Aydıntepe", "Demirözü", "Merkez"],
  "Karaman": ["Ayrancı", "Başyayla", "Ermenek", "Kazımkarabekir", "Merkez", "Sarıveliler"],
  "Kırıkkale": ["Bahşılı", "Balışeyh", "Delice", "Karakeçili", "Keskin", "Merkez", "Sulakyurt", "Yahşihan", "Çelebi"],
  "Batman": ["Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Merkez", "Sason"],
  "Şırnak": ["Beytüşşebap", "Cizre", "Güçlükonak", "Merkez", "Silopi", "Uludere", "İdil"],
  "Bartın": ["Amasra", "Kurucaşile", "Merkez", "Ulus"],
  "Ardahan": ["Damal", "Göle", "Hanak", "Merkez", "Posof", "Çıldır"],
  "Iğdır": ["Aralık", "Karakoyunlu", "Merkez", "Tuzluca"],
  "Yalova": ["Altınova", "Armutlu", "Merkez", "Termal", "Çiftlikköy", "Çınarcık"],
  "Karabük": ["Eflani", "Eskipazar", "Merkez", "Ovacık", "Safranbolu", "Yenice"],
  "Kilis": ["Elbeyli", "Merkez", "Musabeyli", "Polateli"],
  "Osmaniye": ["Bahçe", "Düziçi", "Hasanbeyli", "Kadirli", "Merkez", "Sumbas", "Toprakkale"],
  "Düzce": ["Akçakoca", "Cumayeri", "Gölyaka", "Gümüşova", "Kaynaşlı", "Merkez", "Yığılca", "Çilimli"],
}
