# Novagross Admin
[build]
  base = "/"
  command = "cd /opt/build/repo && pnpm install && pnpm -C apps/admin build"
  publish = "apps/admin/.next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  PNPM_VERSION = "9"

[functions]
  directory = "apps/admin/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
